export const HUBS_SEED = [
  { name: 'Hermes / Gabriel Agent System', slug: 'hermes-gabriel', description: 'Core AI agent operating system for skills, automations, workflows, orchestration, QA, research loops, and agent improvement.', category: 'AI Systems', status: 'Active', priority: 'Critical', revenue_potential: 'Infrastructure', color: '#6366f1', icon: 'Bot', next_action: 'Audit all active skills and update LOCKED_UPGRADES.md' },
  { name: 'Colvin Enterprises', slug: 'colvin-enterprises', description: 'Main revenue brand for AI automation, websites, funnels, workflows, CRM systems, business systems, and AI-powered operations.', category: 'Brand', status: 'Revenue Focus', priority: 'Critical', revenue_potential: '$10,000–$50,000/month', color: '#f59e0b', icon: 'Building2', next_action: 'Finalize AI automation offer page and launch LinkedIn outreach sequence' },
  { name: 'LinkedIn Premium Outreach System', slug: 'linkedin-outreach', description: 'One-month LinkedIn Premium lead research and outreach workflow for finding ideal clients, decision-makers, and booked appointments.', category: 'Outreach', status: 'Active', priority: 'High', revenue_potential: '$5,000–$20,000/month pipeline', color: '#0ea5e9', icon: 'Linkedin', next_action: 'Send 5 connection requests to Indiana home service owners today' },
  { name: 'Daily Lead Intelligence Automation', slug: 'daily-lead-intelligence', description: 'Daily research engine for finding, scoring, organizing, and following up with business leads.', category: 'AI Systems', status: 'Active', priority: 'High', revenue_potential: 'Pipeline multiplier', color: '#10b981', icon: 'Search', next_action: 'Review today\'s 25 scored prospects and approve top 5 for outreach' },
  { name: 'Gabriel Creative Studio', slug: 'gabriel-creative', description: 'Campaign and content generation system for flyers, Canva prompts, social posts, emails, SMS, landing pages, image prompts, and video scripts.', category: 'Media', status: 'Active', priority: 'High', revenue_potential: 'Content engine', color: '#ec4899', icon: 'Palette', next_action: 'Build 7-day promo calendar template for Colvin Enterprises' },
  { name: 'Remotion Video Engine', slug: 'remotion-video', description: 'Short-form cinematic video production system for multiple brands using Remotion, OpenAI images, scripts, captions, and motion direction.', category: 'Media', status: 'Active', priority: 'High', revenue_potential: 'Content engine', color: '#8b5cf6', icon: 'Video', next_action: 'Render daily cinematic ads for all three active brands' },
  { name: 'First Keys Indy', slug: 'first-keys-indy', description: 'Housing education and community growth brand focused on homeownership, redlining education, minority buyers, and generational ownership.', category: 'Community', status: 'Building', priority: 'High', revenue_potential: '$2,000–$8,000/month', color: '#f97316', icon: 'Home', next_action: 'Publish first redlining education TikTok and link custom domain' },
  { name: 'FundingReady Indiana', slug: 'funding-ready-indiana', description: 'Indiana grant readiness system for churches, Black-led nonprofits, youth programs, and community organizations.', category: 'Community', status: 'Revenue Focus', priority: 'High', revenue_potential: '$3,500–$15,000/month', color: '#14b8a6', icon: 'HandCoins', next_action: 'Schedule discovery call with first grant audit client' },
  { name: 'Indiana Backflow / Local Service Automation', slug: 'indiana-backflow', description: 'Local service business marketing and automation system for SEO, reminders, follow-up, reviews, and lead capture.', category: 'Technology', status: 'Building', priority: 'Medium', revenue_potential: '$1,000–$5,000/month', color: '#64748b', icon: 'Wrench', next_action: 'Launch Indiana Backflow Directory and add first 50 listings' },
  { name: 'Music Theory Secrets', slug: 'music-theory-secrets', description: 'Music theory, piano education, book marketing, course content, YouTube scripts, chord progressions, lead sheets, and student resources.', category: 'Education', status: 'Active', priority: 'Medium', revenue_potential: '$2,000–$10,000/month', color: '#a855f7', icon: 'Music', next_action: 'Script 30 short TikTok piano lessons and publish first 5' },
  { name: 'AI Preset VST / GloryEngine AI', slug: 'glory-engine-ai', description: 'AI-assisted sound design product for preset recipes, producer tools, Vital presets, Max for Live ideas, DSP notes, and future VST/AU development.', category: 'Technology', status: 'Idea', priority: 'Future', revenue_potential: '$5,000–$25,000 product launch', color: '#ef4444', icon: 'AudioWaveform', next_action: 'Document 20 core preset recipes and MVP feature list' },
  { name: "Girls Got Game / Women's Sports Media", slug: 'girls-got-game', description: "Women's basketball and women's sports media platform for news, WNBA content, player profiles, team coverage, podcasts, and sponsorships.", category: 'Media', status: 'Idea', priority: 'Medium', revenue_potential: '$3,000–$15,000/month (sponsorships)', color: '#f43f5e', icon: 'Trophy', next_action: 'Define editorial voice and publish 3 pilot articles' },
  { name: 'Bible Teaching / Practical Bible Content', slug: 'bible-teaching', description: 'Bible teaching ecosystem for sermon outlines, Holy Spirit teaching, gifts of the Spirit, Sunday school, devotionals, and YouTube scripts.', category: 'Education', status: 'Active', priority: 'Medium', revenue_potential: 'Ministry impact', color: '#eab308', icon: 'BookOpen', next_action: 'Write 5 Holy Spirit teaching outlines for YouTube' },
  { name: 'Yahweh Comics / Samson Anime Project', slug: 'yahweh-comics', description: 'Biblical anime/comic IP. Canonical Samson: African American warrior, dreadlocks, red and green aura, anime/comic style, dramatic biblical action.', category: 'Media', status: 'Idea', priority: 'Future', revenue_potential: 'IP licensing + publishing', color: '#dc2626', icon: 'Sparkles', next_action: 'Complete Samson character bible and draft issue 1 story arc' },
  { name: 'Urban Legacy Day', slug: 'urban-legacy-day', description: 'Estate planning and generational wealth event. Sponsor tiers: Bronze $2,500 · Silver $4,000 · Gold $5,000 · Platinum $7,500 · Diamond $10,000.', category: 'Events', status: 'Active', priority: 'High', revenue_potential: '$20,000–$50,000 per event', color: '#d97706', icon: 'CalendarDays', next_action: 'Follow up on Gold Sponsor pipeline and confirm venue' },
  { name: 'Church / Nonprofit AI + Financial Literacy Systems', slug: 'church-nonprofit-ai', description: 'AI, automation, donor communication, event registration, volunteer onboarding, grant readiness, and financial literacy systems for churches and nonprofits.', category: 'Community', status: 'Revenue Focus', priority: 'High', revenue_potential: '$2,500–$12,000/client', color: '#16a34a', icon: 'Church', next_action: 'Close first Church AI Operations Setup client at $2,500' },
  { name: 'Local Business Automation Templates', slug: 'local-biz-automation', description: 'Productized automation templates for moving, junk removal, HVAC, roofing, cleaning, med spas, tax firms, contractors, real estate, insurance, and backflow companies.', category: 'Technology', status: 'Building', priority: 'High', revenue_potential: '$1,200–$5,000/package', color: '#0891b2', icon: 'Package', next_action: 'Finalize missed-lead recovery template and price at $1,200' },
  { name: 'Credit Repair / Credit Strategy Agent', slug: 'credit-repair-agent', description: 'Future credit education or credit strategy system. COMPLIANCE REVIEW REQUIRED before any launch activity.', category: 'Future', status: 'Future', priority: 'Future', revenue_potential: 'TBD — compliance review first', color: '#6b7280', icon: 'ShieldAlert', next_action: 'BLOCKED — compliance review required before any build activity' },
  { name: 'Human Communication Evaluation Engine', slug: 'comm-eval-engine', description: 'AI system for evaluating messaging, persuasion, clarity, emotional impact, assumptions, logic, outreach, sermons, and sales communication.', category: 'AI Systems', status: 'Building', priority: 'Medium', revenue_potential: '$1,500–$8,000/client', color: '#7c3aed', icon: 'MessageSquare', next_action: 'Build evaluation rubric and test against 5 real outreach samples' },
  { name: 'Genius Prompt Generator', slug: 'genius-prompts', description: 'Internal prompt factory for business, marketing, coding, research, music, Bible teaching, automation, image generation, Remotion, Claude, Codex, Lovable, and Perplexity prompts.', category: 'AI Systems', status: 'Active', priority: 'Medium', revenue_potential: 'Internal leverage multiplier', color: '#0d9488', icon: 'Zap', next_action: 'Organize 50 best prompts into categorized library' },
]

export const TASKS_SEED = [
  // Hermes / Gabriel
  { hub_slug: 'hermes-gabriel', title: 'Audit all active Gabriel skills and flag outdated logic', status: 'To Do', priority: 'Critical', due_date: null, next_action: 'Open LOCKED_UPGRADES.md and compare to current skill files' },
  { hub_slug: 'hermes-gabriel', title: 'Update GABRIEL_BOOT.md trigger map with new CRM routes', status: 'To Do', priority: 'High', due_date: null, next_action: 'Add /hubs, /tasks, /revenue to context router' },
  // Colvin Enterprises
  { hub_slug: 'colvin-enterprises', title: 'Finalize AI automation services offer page copy', status: 'In Progress', priority: 'Critical', due_date: null, next_action: 'Add 3 case study placeholders and pricing tiers' },
  { hub_slug: 'colvin-enterprises', title: 'Launch LinkedIn outreach sequence for AI automation clients', status: 'To Do', priority: 'High', due_date: null, next_action: 'Draft 5 connection request messages for Indiana home service owners' },
  // LinkedIn Outreach
  { hub_slug: 'linkedin-outreach', title: 'Send 5 personalized connection requests to Indiana business owners', status: 'To Do', priority: 'High', due_date: null, next_action: 'Pull top 5 from Daily Lead Intelligence and personalize messages' },
  { hub_slug: 'linkedin-outreach', title: 'Build LinkedIn message sequence for warm leads', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'Write 3-touch follow-up sequence for unanswered connections' },
  // Daily Lead Intelligence
  { hub_slug: 'daily-lead-intelligence', title: 'Review and score today\'s 25 prospect batch', status: 'To Do', priority: 'High', due_date: null, next_action: 'Mark top 5 for outreach approval in CRM' },
  { hub_slug: 'daily-lead-intelligence', title: 'Configure lead scoring weights for Indiana home service segment', status: 'Backlog', priority: 'Medium', due_date: null, next_action: 'Update scoring criteria in Gabriel lead skill' },
  // Gabriel Creative Studio
  { hub_slug: 'gabriel-creative', title: 'Build 7-day promo content calendar for Colvin Enterprises', status: 'To Do', priority: 'High', due_date: null, next_action: 'Define offer, audience, and hook angles for each day' },
  { hub_slug: 'gabriel-creative', title: 'Generate 10 Canva flyer prompts for Urban Legacy Day', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'Use Gabriel Creative Studio skill with event brief' },
  // Remotion Video Engine
  { hub_slug: 'remotion-video', title: 'Render daily cinematic ad for Colvin Enterprises', status: 'To Do', priority: 'High', due_date: null, next_action: 'Run render:colvin:vertical script and review output' },
  { hub_slug: 'remotion-video', title: 'Create Remotion template for First Keys Indy homebuyer content', status: 'In Progress', priority: 'Medium', due_date: null, next_action: 'Adapt existing vertical template with FKI brand colors' },
  // First Keys Indy
  { hub_slug: 'first-keys-indy', title: 'Publish first redlining education TikTok video', status: 'To Do', priority: 'High', due_date: null, next_action: 'Use rendered Remotion video and post with caption' },
  { hub_slug: 'first-keys-indy', title: 'Link custom domain to First Keys Indy Vercel deployment', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'Add DNS records and verify SSL certificate' },
  // FundingReady Indiana
  { hub_slug: 'funding-ready-indiana', title: 'Schedule discovery call with first grant audit prospect', status: 'To Do', priority: 'Critical', due_date: null, next_action: 'Send Calendly link to qualified nonprofit contact' },
  { hub_slug: 'funding-ready-indiana', title: 'Build grant audit intake form and checklist', status: 'Backlog', priority: 'Medium', due_date: null, next_action: 'Draft 20-point grant readiness assessment' },
  // Indiana Backflow
  { hub_slug: 'indiana-backflow', title: 'Add first 50 listings to Indiana Backflow Directory', status: 'In Progress', priority: 'High', due_date: null, next_action: 'Scrape IDEM license database for certified testers' },
  { hub_slug: 'indiana-backflow', title: 'Set up automated review reminder for backflow clients', status: 'Backlog', priority: 'Low', due_date: null, next_action: 'Build SMS/email sequence for annual test reminders' },
  // Music Theory Secrets
  { hub_slug: 'music-theory-secrets', title: 'Script 5 TikTok piano lessons from chord progression library', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'Select 5 beginner-friendly chord progressions to teach' },
  { hub_slug: 'music-theory-secrets', title: 'Publish music theory book landing page to website', status: 'Backlog', priority: 'Low', due_date: null, next_action: 'Write sales copy and connect to Gumroad or Stripe' },
  // GloryEngine AI
  { hub_slug: 'glory-engine-ai', title: 'Document 20 core preset recipes with signal chain specs', status: 'Backlog', priority: 'Future', due_date: null, next_action: 'Create preset doc template with genre, mood, and chain' },
  { hub_slug: 'glory-engine-ai', title: 'Define MVP feature list for GloryEngine VST product', status: 'Backlog', priority: 'Future', due_date: null, next_action: 'Research competing AI VST products and identify gaps' },
  // Girls Got Game
  { hub_slug: 'girls-got-game', title: 'Define editorial voice and content pillars for Girls Got Game', status: 'Backlog', priority: 'Medium', due_date: null, next_action: 'Write brand voice guide and 5 content pillar descriptions' },
  { hub_slug: 'girls-got-game', title: 'Publish 3 pilot articles on WNBA player profiles', status: 'Backlog', priority: 'Low', due_date: null, next_action: 'Select 3 players and draft 500-word profiles with stats' },
  // Bible Teaching
  { hub_slug: 'bible-teaching', title: 'Write 5 Holy Spirit teaching outlines for YouTube', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'Use Gabriel Bible skill to generate outlines for Acts 2, 1 Cor 12-14' },
  { hub_slug: 'bible-teaching', title: 'Create devotional email series for Sunday school teachers', status: 'Backlog', priority: 'Low', due_date: null, next_action: 'Draft 7-part series with scripture, question, and application' },
  // Yahweh Comics
  { hub_slug: 'yahweh-comics', title: 'Complete Samson character bible with design specs', status: 'Backlog', priority: 'Future', due_date: null, next_action: 'Document physical attributes, power system, origin story' },
  { hub_slug: 'yahweh-comics', title: 'Draft issue 1 story arc and panel breakdowns', status: 'Backlog', priority: 'Future', due_date: null, next_action: 'Outline 3-act structure for first issue based on Judges 13-16' },
  // Urban Legacy Day
  { hub_slug: 'urban-legacy-day', title: 'Follow up with Gold Sponsor pipeline contacts', status: 'To Do', priority: 'Critical', due_date: null, next_action: 'Send personalized follow-up to 3 open sponsor conversations' },
  { hub_slug: 'urban-legacy-day', title: 'Confirm venue and lock event date', status: 'In Progress', priority: 'High', due_date: null, next_action: 'Contact venue manager and get contract signed' },
  // Church / Nonprofit AI
  { hub_slug: 'church-nonprofit-ai', title: 'Close first Church AI Operations Setup client at $2,500', status: 'To Do', priority: 'Critical', due_date: null, next_action: 'Send proposal to pastor meeting booked for next week' },
  { hub_slug: 'church-nonprofit-ai', title: 'Build church onboarding checklist and workflow template', status: 'Backlog', priority: 'Medium', due_date: null, next_action: 'Document standard 5-step church AI onboarding process' },
  // Local Business Automation
  { hub_slug: 'local-biz-automation', title: 'Finalize missed-lead recovery automation template', status: 'In Progress', priority: 'High', due_date: null, next_action: 'Build n8n or Zapier flow and price at $1,200' },
  { hub_slug: 'local-biz-automation', title: 'Create sales one-pager for HVAC and roofing automation package', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'List 5 automation wins specific to home service businesses' },
  // Comm Eval Engine
  { hub_slug: 'comm-eval-engine', title: 'Build evaluation rubric for outreach message scoring', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'Define 10 evaluation dimensions with 1-10 scoring criteria' },
  { hub_slug: 'comm-eval-engine', title: 'Test rubric against 5 real outreach samples', status: 'Backlog', priority: 'Medium', due_date: null, next_action: 'Pull 5 LinkedIn messages from outreach history and score each' },
  // Genius Prompts
  { hub_slug: 'genius-prompts', title: 'Categorize and tag 50 best prompts into library', status: 'To Do', priority: 'Medium', due_date: null, next_action: 'Create category taxonomy: business, marketing, coding, media' },
  { hub_slug: 'genius-prompts', title: 'Build prompt submission workflow for new prompt additions', status: 'Backlog', priority: 'Low', due_date: null, next_action: 'Create prompts intake form that saves directly to Supabase' },
  // Credit Repair (BLOCKED)
  { hub_slug: 'credit-repair-agent', title: 'BLOCKED: Schedule compliance review before any build activity', status: 'Blocked', priority: 'Future', due_date: null, next_action: 'Do not proceed until legal/compliance review is complete' },
  { hub_slug: 'credit-repair-agent', title: 'Research FTC credit repair regulations and document findings', status: 'Blocked', priority: 'Future', due_date: null, next_action: 'Review CROA requirements before building any consumer-facing feature' },
]

export const RESEARCH_SEED = [
  { hub_slug: 'colvin-enterprises', title: 'Indiana small business AI adoption rate 2024-2025', source: 'Perplexity research', summary: 'Approximately 34% of Indiana SMBs have experimented with AI tools. Most cite time savings and lead follow-up as top use cases. Adoption highest in professional services and home services.', evidence_quality: 'Strong Evidence', tags: ['indiana', 'smb', 'ai-adoption'], action_items: 'Use stat in sales pitch: 34% of local businesses are experimenting with AI — position as competitive advantage' },
  { hub_slug: 'funding-ready-indiana', title: 'Indiana philanthropic giving to Black-led nonprofits 2023', source: 'Indiana Philanthropy Alliance report', summary: 'Black-led nonprofits in Indiana receive approximately 1.5% of total philanthropic giving despite representing 12% of nonprofit sector. CDFI and government grant programs are most accessible entry points.', evidence_quality: 'Verified', tags: ['grants', 'nonprofits', 'indiana', 'equity'], action_items: 'Lead with CDFI and HUD grants for first clients — highest approval rate for community orgs' },
  { hub_slug: 'urban-legacy-day', title: 'Estate planning rates among Black Americans under 50', source: 'Gallup / AARP 2023 survey', summary: 'Only 27% of Black Americans under 50 have a will. Top barriers: cost perception, distrust of legal system, lack of trusted referrals. Events + community format significantly increase conversion.', evidence_quality: 'Verified', tags: ['estate-planning', 'wealth-gap', 'community'], action_items: 'Lead with "no will = wealth gap" framing in Urban Legacy Day marketing' },
  { hub_slug: 'church-nonprofit-ai', title: 'Church administrative burden and staff capacity constraints', source: 'Barna Group 2023 / Church Answers Research', summary: 'Average church under 500 members runs with 1.5 full-time administrative staff. Top time sinks: event registration, donor follow-up, bulletin prep, volunteer coordination. AI tools not yet widely adopted.', evidence_quality: 'Strong Evidence', tags: ['church', 'admin', 'automation'], action_items: 'Sell time savings first — frame AI system as "virtual admin assistant" at fraction of staff cost' },
  { hub_slug: 'linkedin-outreach', title: 'LinkedIn Premium Sales Navigator response rates by industry', source: 'LinkedIn internal data / HubSpot benchmark report', summary: 'Personalized InMail messages see 18-25% open rates vs 3% cold email. Connection requests with personalized notes convert at 38% vs 22% generic. Home services and construction respond best on Tuesday-Thursday mornings.', evidence_quality: 'Strong Evidence', tags: ['linkedin', 'outreach', 'response-rates'], action_items: 'Send connection requests Tuesday-Thursday 8-10am. Always personalize with specific business detail.' },
  { hub_slug: 'music-theory-secrets', title: 'Piano education content performance on TikTok 2024', source: 'Creator observation + TikTok analytics reports', summary: 'Short-form piano content (under 45 seconds) with chord progression reveal format performs 3x better than tutorial format. Text overlay hooks drive 70% of saves. Beginners over-index for engagement vs intermediate players.', evidence_quality: 'Strong Evidence', tags: ['tiktok', 'piano', 'content-strategy'], action_items: 'Use chord reveal format for all piano TikToks. Target absolute beginners. Lead with "you can play this in 5 minutes" hook.' },
  { hub_slug: 'first-keys-indy', title: 'Marion County homeownership gap by race 2023', source: 'HAND Inc. / City of Indianapolis housing report', summary: 'White homeownership rate in Marion County: 68%. Black homeownership rate: 38%. 30-point gap driven by historical redlining, lending discrimination, and generational wealth absence. State of Indiana offers up to $15,000 DPA for first-time buyers.', evidence_quality: 'Verified', tags: ['homeownership', 'race', 'indianapolis', 'dpa'], action_items: 'Lead all FKI content with the 30-point gap stat. DPA programs are the solution hook.' },
  { hub_slug: 'hermes-gabriel', title: 'Claude API context window utilization best practices', source: 'Anthropic documentation / internal testing', summary: 'Claude claude-sonnet-4-6 supports 200K token context. Optimal performance at 40-60% context utilization. Skills-based architecture reduces token waste by 60% vs monolithic prompts. Structured output reduces hallucination rate significantly.', evidence_quality: 'Verified', tags: ['claude', 'api', 'architecture', 'performance'], action_items: 'Keep skill files under 2000 tokens each. Use structured output for all data extraction tasks.' },
  { hub_slug: 'remotion-video', title: 'Short-form video completion rate by length 2024', source: 'TikTok creator insights / Meta business data', summary: 'Videos under 15 seconds see 72% completion rate. 15-30 seconds: 54%. 30-60 seconds: 38%. Cinematic B-roll hooks in first 2 seconds increase completion by 34%. Text overlay on every frame increases saves by 2.3x.', evidence_quality: 'Strong Evidence', tags: ['video', 'completion-rate', 'tiktok', 'reels'], action_items: 'Target 12-18 second videos for maximum completion. Always add text overlay. Use cinematic first frame.' },
  { hub_slug: 'local-biz-automation', title: 'Missed lead cost for home service businesses', source: 'Signpost / CallRail industry report 2023', summary: 'Average home service business misses 28% of inbound leads due to missed calls and slow response. A missed HVAC job averages $800. A missed lead recovery automation pays for itself in first recovered job.', evidence_quality: 'Strong Evidence', tags: ['home-service', 'lead-recovery', 'roi'], action_items: 'Lead pitch with: "You miss 1 in 4 calls. One recovered HVAC job pays for this entire system." Price at $1,200.' },
  { hub_slug: 'glory-engine-ai', title: 'VST plugin market size and AI music tools growth 2024', source: 'Music Technology World / Statista market data', summary: 'Global VST plugin market: $1.8B in 2024, growing 12% annually. AI-assisted music tools segment growing at 34%. Producer-focused AI tools with preset management see highest NPS scores.', evidence_quality: 'Reasoned Inference', tags: ['vst', 'market-size', 'ai-music'], action_items: 'Position GloryEngine as AI preset intelligence layer, not a synthesizer. Target intermediate producers who own Vital/Serum.' },
  { hub_slug: 'daily-lead-intelligence', title: 'Lead response time impact on conversion rate', source: 'InsideSales.com / HBR research synthesis', summary: 'Leads contacted within 5 minutes of showing intent are 100x more likely to convert than leads contacted after 30 minutes. Daily lead scoring + same-day outreach is minimum viable standard.', evidence_quality: 'Verified', tags: ['lead-response', 'conversion', 'timing'], action_items: 'Gabriel daily run must approve top leads for outreach same day. Build urgency into scoring algorithm.' },
  { hub_slug: 'comm-eval-engine', title: 'Persuasion research: EAST framework for behavior change', source: 'UK Behavioural Insights Team / Cialdini synthesis', summary: 'Easy, Attractive, Social, Timely (EAST) framework predicts communication effectiveness better than traditional persuasion models. Social proof and loss aversion are most powerful levers for B2B and nonprofit audiences.', evidence_quality: 'Verified', tags: ['persuasion', 'communication', 'frameworks', 'b2b'], action_items: 'Build EAST scoring into Communication Evaluation Engine rubric. Weight social proof and loss aversion highest.' },
  { hub_slug: 'genius-prompts', title: 'Prompt engineering patterns that reduce hallucination', source: 'Anthropic research papers / DeepMind benchmarks', summary: 'Chain-of-thought prompting reduces factual errors by 40%. Role specification + output format constraints reduce hallucination by 55% on complex reasoning tasks. Few-shot examples outperform zero-shot for structured data extraction.', evidence_quality: 'Strong Evidence', tags: ['prompting', 'hallucination', 'chain-of-thought'], action_items: 'All Genius Prompts must include: role, output format, and at least 1 few-shot example for factual tasks.' },
  { hub_slug: 'girls-got-game', title: 'WNBA viewership growth and media opportunity 2024', source: 'ESPN analytics / Nielsen Sports', summary: 'WNBA 2024 season saw 121% viewership increase driven by Caitlin Clark and Angel Reese. Social media engagement up 400% year-over-year. Independent sports media outlets growing 3x faster than traditional outlets.', evidence_quality: 'Verified', tags: ['wnba', 'viewership', 'media', 'opportunity'], action_items: 'Launch Girls Got Game now — wave timing is optimal. Lead with WNBA coverage to ride organic search growth.' },
  { hub_slug: 'bible-teaching', title: 'YouTube Bible teaching content growth and audience profile', source: 'YouTube analytics / creator reports', summary: 'Bible teaching channels with 10K-50K subscribers generate $1,500-$8,000/month in ad revenue + digital product sales. Practical application format (verse → principle → action) outperforms traditional sermon format by 60% on retention.', evidence_quality: 'Strong Evidence', tags: ['youtube', 'bible', 'monetization', 'content'], action_items: 'Use verse-principle-action format for all Bible YouTube content. Target 8-12 minute length for ad revenue optimization.' },
  { hub_slug: 'indiana-backflow', title: 'Indiana backflow testing market size and compliance rates', source: 'IDEM / local research', summary: 'Indiana has approximately 45,000 commercial properties required to test backflow preventers annually. Compliance rate estimated at 60-70%. Market is highly fragmented — no dominant digital directory exists.', evidence_quality: 'Reasoned Inference', tags: ['backflow', 'indiana', 'market-size', 'compliance'], action_items: 'Directory owns the SEO and referral moat. Build listings before competitors discover the gap.' },
  { hub_slug: 'yahweh-comics', title: 'Biblical IP and faith-based entertainment market 2024', source: 'ICv2 / Publishers Weekly faith category data', summary: 'Faith-based entertainment market exceeded $2.5B in 2023. Comics and graphic novels with faith themes growing 18% annually. Anime-inspired art style with Black protagonists represents underserved gap in market.', evidence_quality: 'Reasoned Inference', tags: ['comics', 'faith', 'market', 'ip'], action_items: 'Position Yahweh Comics as first faith-based anime IP with Black biblical heroes. Target Kickstarter for initial funding.' },
  { hub_slug: 'colvin-enterprises', title: 'Indianapolis SMB digital marketing spend and agency market', source: 'Local market research / BIA Advisory Services', summary: 'Indianapolis metro SMBs spend average $2,400/month on digital marketing services. Top unmet needs: AI automation, CRM setup, and lead follow-up systems. Agency saturation is low outside of downtown corridor.', evidence_quality: 'Reasoned Inference', tags: ['indianapolis', 'smb', 'market', 'agency'], action_items: 'Target suburban Indianapolis home service businesses — underserved by agencies, high willingness to pay for automation.' },
  { hub_slug: 'church-nonprofit-ai', title: 'Church financial literacy program adoption and outcomes', source: 'Dave Ramsey Group / Crown Financial research', summary: 'Churches running Financial Peace University programs see 34% increase in congregant giving over 18 months. Financial literacy programs increase pastor credibility and church retention. Programs generate $2,000-$8,000 in licensing and event revenue annually.', evidence_quality: 'Strong Evidence', tags: ['church', 'financial-literacy', 'fpu', 'revenue'], action_items: 'Offer FPU/Crown program support as upsell to AI Operations Setup. Revenue per church could reach $10,000+ annually.' },
]

export const PROMPTS_SEED = [
  { hub_slug: 'colvin-enterprises', title: 'AI Automation Cold Outreach — Indiana Home Service', category: 'Outreach', prompt_text: 'You are Alfred Colvin, founder of Colvin Enterprises. Write a personalized LinkedIn connection request to [BUSINESS_OWNER] who owns [BUSINESS_NAME], a [BUSINESS_TYPE] in [CITY], Indiana. Reference something specific about their business. Position AI automation as solving missed leads and slow follow-up. Be direct, warm, and professional. Under 300 characters.', model_target: 'claude-sonnet-4-6', use_case: 'LinkedIn outreach first touch', status: 'Active' },
  { hub_slug: 'colvin-enterprises', title: 'Proposal Follow-Up Message — 48 Hours After Sending', category: 'Sales', prompt_text: 'Write a follow-up message for a business owner who received an AI automation proposal 48 hours ago and has not responded. The proposal was for [PACKAGE_NAME] at [PRICE]. Reference the specific pain point we discussed: [PAIN_POINT]. Keep it 3 sentences max. End with a clear yes/no question to reduce friction.', model_target: 'claude-sonnet-4-6', use_case: 'Sales follow-up', status: 'Active' },
  { hub_slug: 'gabriel-creative', title: 'Short-Form Video Hook Generator — 15 Variations', category: 'Content', prompt_text: 'Generate 15 short-form video hook lines for [BRAND] promoting [OFFER/MESSAGE]. Target audience: [AUDIENCE]. Platform: TikTok/Reels. Format: One line per hook, under 10 words. Mix patterns: curiosity gap, bold claim, before/after, number hook, direct challenge. No filler words. No emoji.', model_target: 'claude-sonnet-4-6', use_case: 'Remotion video scripts', status: 'Active' },
  { hub_slug: 'gabriel-creative', title: 'Instagram Caption — Engagement Optimized', category: 'Content', prompt_text: 'Write an Instagram caption for [BRAND] about [TOPIC]. Opening line must stop the scroll — no "I" to start. Body: 3-4 short paragraphs with line breaks. Include a question at the end to drive comments. Hashtags: generate 8 targeted hashtags, mix 3 niche + 3 mid + 2 broad. Tone: [TONE].', model_target: 'claude-sonnet-4-6', use_case: 'Social media content', status: 'Active' },
  { hub_slug: 'music-theory-secrets', title: 'Piano TikTok Lesson Script — Chord Reveal Format', category: 'Content', prompt_text: 'Write a 15-second TikTok piano lesson script about [CHORD_PROGRESSION]. Format: [HOOK line] → [Show the chord] → [Name it] → [Play example song that uses it] → [CTA: "Follow for more"]. Keep script to 40 words max. Target absolute beginners. No music theory jargon.', model_target: 'claude-sonnet-4-6', use_case: 'TikTok piano content', status: 'Active' },
  { hub_slug: 'funding-ready-indiana', title: 'Grant Readiness Assessment Report', category: 'Research', prompt_text: 'You are a grant readiness consultant. Analyze the following nonprofit\'s information and provide a detailed grant readiness assessment: [NONPROFIT_INFO]. Evaluate: 501(c)(3) status, financial statements quality, program documentation, board governance, impact measurement, and narrative capacity. Rate each area 1-10 with specific improvement actions. Output as structured report.', model_target: 'claude-sonnet-4-6', use_case: 'Client grant audits', status: 'Active' },
  { hub_slug: 'first-keys-indy', title: 'Homebuyer Education Content — Redlining History Hook', category: 'Content', prompt_text: 'Write a TikTok script explaining how redlining affected [NEIGHBORHOOD] in Indianapolis. Length: 30-45 seconds. Format: shocking stat hook → brief history → current gap → solution (homeownership) → CTA to First Keys Indy. Use plain language. No academic tone. End with empowerment, not victimhood.', model_target: 'claude-sonnet-4-6', use_case: 'First Keys Indy social content', status: 'Active' },
  { hub_slug: 'urban-legacy-day', title: 'Sponsorship Pitch Email — Decision Maker', category: 'Sales', prompt_text: 'Write a sponsorship pitch email for Urban Legacy Day estate planning event to [COMPANY_TYPE] at [COMPANY_NAME]. Sponsorship tier: [TIER] at [PRICE]. Emphasize brand alignment with Black wealth building, audience of 200+ Indianapolis professionals, and specific sponsor benefits. Keep to 250 words. Include a specific call to action with deadline.', model_target: 'claude-sonnet-4-6', use_case: 'Event sponsorship outreach', status: 'Active' },
  { hub_slug: 'church-nonprofit-ai', title: 'Church AI Discovery Call Prep Brief', category: 'Sales', prompt_text: 'Prepare a 10-minute discovery call brief for a church with the following profile: [CHURCH_PROFILE]. Identify: 3 likely pain points, 2 budget objections to preempt, key decision maker concerns, and the single strongest ROI statement for this church. Format as bullet points for easy reference during call.', model_target: 'claude-sonnet-4-6', use_case: 'Church sales prep', status: 'Active' },
  { hub_slug: 'bible-teaching', title: 'Bible Teaching Outline — Practical Application Format', category: 'Content', prompt_text: 'Create a Bible teaching outline on [TOPIC] from [SCRIPTURE_REFERENCE]. Format: Title → Main Truth (one sentence) → 3 Key Points (each with: verse, principle, modern application, discussion question) → Closing Challenge (actionable this week). Length: 400-600 words. Tone: conversational, practical, non-religious jargon.', model_target: 'claude-sonnet-4-6', use_case: 'YouTube Bible content', status: 'Active' },
  { hub_slug: 'genius-prompts', title: 'Research Loop Deep Dive — Market Opportunity Analysis', category: 'Research', prompt_text: 'Conduct a market opportunity analysis for [BUSINESS_IDEA] in [MARKET/GEOGRAPHY]. Structure your analysis as: 1) Market size estimate with data sources 2) Top 3 customer segments with demographics and pain points 3) Competitive landscape — 5 competitors with weaknesses 4) Unique advantage window — why now? 5) Revenue model options with estimated ranges 6) Biggest risk and mitigation. Cite evidence quality for each claim.', model_target: 'claude-sonnet-4-6', use_case: 'Business research', status: 'Active' },
  { hub_slug: 'comm-eval-engine', title: 'Outreach Message Clarity Evaluator', category: 'Evaluation', prompt_text: 'Evaluate this outreach message against 10 criteria: Clarity (1-10), Personalization (1-10), Value Proposition clarity (1-10), CTA strength (1-10), Length appropriateness (1-10), Tone match for audience (1-10), Social proof usage (1-10), Loss aversion framing (1-10), Opening line strength (1-10), Overall persuasion score (1-10). Provide score, one-sentence rationale, and specific rewrite suggestion for any score below 7.\n\nMessage to evaluate:\n[MESSAGE]', model_target: 'claude-sonnet-4-6', use_case: 'Message quality control', status: 'Active' },
  { hub_slug: 'daily-lead-intelligence', title: 'Lead Qualification Scoring Brief', category: 'Research', prompt_text: 'Score this lead on a 1-10 scale across 5 dimensions: Fit (do they match ideal client profile), Pain Signal (evidence of the problem we solve), Reachability (can we contact them), Budget Signal (evidence of spend capacity), Timing Signal (urgency indicators). Provide overall score 1-10. Flag if human review required.\n\nLead data:\n[LEAD_DATA]', model_target: 'claude-sonnet-4-6', use_case: 'Gabriel lead scoring', status: 'Active' },
  { hub_slug: 'hermes-gabriel', title: 'Gabriel Session Start Checklist Prompt', category: 'Operations', prompt_text: 'You are Gabriel starting a new work session for Alfred Colvin. Before taking any action: 1) State which hub or task you are working on 2) Confirm what the previous state was 3) List what you plan to do this session 4) Flag any locked upgrade rules that apply 5) State your confidence level and evidence quality for each planned action. Wait for Alfred\'s confirmation before proceeding.', model_target: 'claude-sonnet-4-6', use_case: 'Agent session management', status: 'Active' },
  { hub_slug: 'local-biz-automation', title: 'Automation ROI Calculator Prompt for Prospect', category: 'Sales', prompt_text: 'Calculate the ROI of a missed-lead recovery automation for [BUSINESS_TYPE] with these inputs: Monthly inbound calls: [CALLS], Current close rate: [RATE]%, Average job value: $[JOB_VALUE], Estimated missed call rate: 28%. Show: Monthly leads missed, Revenue missed per month, ROI of $1,200 automation package (months to break even), 12-month net gain. Format as clean calculation with clear final recommendation.', model_target: 'claude-sonnet-4-6', use_case: 'Sales automation pitch', status: 'Active' },
  { hub_slug: 'remotion-video', title: 'Remotion Video Scene Direction Brief', category: 'Content', prompt_text: 'Write a Remotion video scene direction brief for a [LENGTH] second video about [TOPIC] for [BRAND]. Include: Scene 1 (0-3s hook): visual description + text overlay + motion type. Scene 2 (3-8s): visual + key message + transition. Scene 3 (8-12s): social proof or feature. Scene 4 (12-15s): CTA + brand logo placement. Color palette: [COLORS]. Mood: [MOOD].', model_target: 'claude-sonnet-4-6', use_case: 'Remotion script generation', status: 'Active' },
  { hub_slug: 'girls-got-game', title: 'WNBA Player Profile Article Template', category: 'Content', prompt_text: 'Write a 500-word profile of WNBA player [PLAYER_NAME] for Girls Got Game. Include: Opening hook (most impressive recent achievement), Background (college, draft position, journey), Playing style analysis (3 specific strengths), Current season stats with context, One quote or moment that shows character, Future outlook. Tone: enthusiastic but credible. No fluff.', model_target: 'claude-sonnet-4-6', use_case: 'Editorial content', status: 'Active' },
  { hub_slug: 'indiana-backflow', title: 'Local SEO Blog Post — Indiana Backflow Testing', category: 'Content', prompt_text: 'Write a 600-word SEO-optimized blog post targeting the keyword "[CITY] backflow testing" for Indiana Backflow Directory. Include: What backflow prevention is (plain language), why annual testing is required by Indiana law, how to find a certified tester, what happens if you skip testing (penalties), and a directory CTA. Use H2 headers. Natural keyword density.', model_target: 'claude-sonnet-4-6', use_case: 'Indiana Backflow SEO content', status: 'Active' },
  { hub_slug: 'yahweh-comics', title: 'Samson Comic Script — Panel Direction', category: 'Content', prompt_text: 'Write a 6-panel comic script for a Samson scene from Judges [CHAPTER:VERSE]. Style: anime-inspired, cinematic. Samson is depicted as a tall African American man with long dreadlocks, wearing ancient warrior garb with red and green color accents. Each panel: Panel direction (wide/close/medium), visual description, dialogue or caption, emotional tone. Make it dramatic and biblically accurate.', model_target: 'claude-sonnet-4-6', use_case: 'Yahweh Comics script', status: 'Active' },
  { hub_slug: 'colvin-enterprises', title: 'Website Audit Brief for Prospect', category: 'Sales', prompt_text: 'Conduct a quick website audit for [WEBSITE_URL] owned by [BUSINESS_NAME]. Evaluate: Speed impression, Mobile readiness (visual), CTA clarity, Trust signals (testimonials, credentials), Lead capture mechanism, Local SEO signals. Rate each 1-10. Provide 3 specific improvement recommendations Colvin Enterprises could address. Format as a 1-page brief suitable to share with prospect.', model_target: 'claude-sonnet-4-6', use_case: 'Pre-sales discovery tool', status: 'Active' },
]

export const AUTOMATIONS_SEED = [
  { hub_slug: 'hermes-gabriel', name: 'Gabriel Daily Orchestration Run', trigger_type: 'Scheduled (7:00 AM CST)', workflow_description: 'Runs daily lead scoring, content generation, outreach drafting, and gabriel_memory update. Outputs batch of items for Alfred approval.', tools_required: ['claude-api', 'supabase', 'perplexity'], status: 'Active' },
  { hub_slug: 'daily-lead-intelligence', name: 'Lead Scoring and Deduplication Pipeline', trigger_type: 'Triggered by Gabriel daily run', workflow_description: 'Fetches raw leads from sources, scores each 1-10 on fit/pain/budget dimensions, deduplicates against existing leads table, flags top 5 for outreach approval.', tools_required: ['claude-api', 'supabase', 'perplexity'], status: 'Active' },
  { hub_slug: 'linkedin-outreach', name: 'LinkedIn Connection Request Queue', trigger_type: 'Manual trigger (daily)', workflow_description: 'Takes top 5 scored leads, generates personalized connection request messages, queues for Alfred review before sending. Never auto-sends.', tools_required: ['claude-api', 'supabase'], status: 'Active' },
  { hub_slug: 'colvin-enterprises', name: 'New Lead Welcome Email Sequence', trigger_type: 'Lead status changes to Contacted', workflow_description: 'Sends 3-email welcome/follow-up sequence over 7 days when a lead enters Contacted status. All emails require Alfred approval before sending via Resend API.', tools_required: ['resend', 'supabase', 'claude-api'], status: 'Draft' },
  { hub_slug: 'local-biz-automation', name: 'Missed Call Recovery Automation Template', trigger_type: 'Missed call webhook from Twilio', workflow_description: 'Detects missed calls via Twilio webhook, sends SMS within 60 seconds, follows up with email if no response in 2 hours, logs recovery attempt. Template for client deployment.', tools_required: ['twilio', 'sendgrid', 'supabase', 'n8n'], status: 'Draft' },
  { hub_slug: 'funding-ready-indiana', name: 'Grant Deadline Tracker and Alert', trigger_type: 'Daily scheduled check', workflow_description: 'Monitors grant database for deadlines within 30/14/7 days for active clients. Sends alert email to Alfred and client contact. Generates checklist of required documents.', tools_required: ['supabase', 'resend', 'claude-api'], status: 'Draft' },
  { hub_slug: 'urban-legacy-day', name: 'Sponsor Follow-Up Sequence', trigger_type: 'Sponsor status changes to Contacted', workflow_description: 'Sends 3-touch follow-up to event sponsors over 10 days. Touch 1: Value recap. Touch 2: Social proof (other sponsors). Touch 3: Urgency/deadline. All require Alfred approval.', tools_required: ['resend', 'supabase'], status: 'Draft' },
  { hub_slug: 'church-nonprofit-ai', name: 'Church Onboarding Workflow', trigger_type: 'New church client signed', workflow_description: 'Triggers upon contract signature: sends welcome packet, schedules kickoff call, creates client project in CRM, assigns 5-step onboarding task sequence, generates initial AI audit brief.', tools_required: ['supabase', 'resend', 'claude-api'], status: 'Draft' },
  { hub_slug: 'first-keys-indy', name: 'Homebuyer Lead Nurture Sequence', trigger_type: 'New email subscriber from landing page', workflow_description: 'Delivers 5-part email series over 14 days: homeownership readiness quiz, DPA programs guide, credit score education, local lender resources, and event CTA. Tracks open and click rates.', tools_required: ['resend', 'supabase'], status: 'Draft' },
  { hub_slug: 'remotion-video', name: 'Daily Cinematic Ad Render Pipeline', trigger_type: 'Manual trigger or scheduled', workflow_description: 'Generates video brief via Gabriel, creates Remotion JSON config, triggers local render via API, deposits MP4 in output folder, creates approval item in Hermes CRM for Alfred review.', tools_required: ['remotion', 'claude-api', 'supabase', 'openai'], status: 'Active' },
]

export const REVENUE_SEED = [
  { title: 'Colvin Enterprises AI Workflow Setup', amount: 1500, stage: 'Proposal', probability: 60, notes: 'Client reviewing proposal', hub_slug: 'colvin-enterprises' },
  { title: 'FundingReady Indiana Grant Audit', amount: 3500, stage: 'Discovery', probability: 40, notes: 'Intro call completed', hub_slug: 'funding-ready-indiana' },
  { title: 'Urban Legacy Day Gold Sponsor', amount: 5000, stage: 'Negotiation', probability: 70, notes: 'Sponsor reviewing tier details', hub_slug: 'urban-legacy-day' },
  { title: 'Church AI Operations Setup', amount: 2500, stage: 'Discovery', probability: 50, notes: 'Pastor meeting next week', hub_slug: 'church-nonprofit-ai' },
  { title: 'Local Business Missed-Lead Recovery Package', amount: 1200, stage: 'New', probability: 30, notes: 'Indiana home service prospect', hub_slug: 'local-biz-automation' },
]
